//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class facturacion
    {
        public int fkpk_id_comanda { get; set; }
        public int propina { get; set; }
        public int cobro { get; set; }
    
        public virtual comanda comanda { get; set; }
    }
}
