//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int id { get; set; }
        public int fk_id_producto { get; set; }
        public int cantidad { get; set; }
        public int fk_id_comanda { get; set; }
    
        public virtual comanda comanda { get; set; }
        public virtual productos productos { get; set; }
    }
}
