//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restaurante1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos_mesa
    {
        public int numero_mesa { get; set; }
        public int cantidad { get; set; }
        public string producto { get; set; }
        public int precio_venta { get; set; }
    }
}
